//package com.abcfurniture.server.enums;
//
//public enum ProductSubCategoryEnum {
//    classic_and_rustic_kitchens,
//    modern_kitchens,
//    sinks,
//    mixing_taps,
//    kitchen_worktops,
//    accessories,
//    bedroom_sets,
//    beds,
//    mattresses,
//    wardrobes,
//    wardrobe_closets,
//    chests_and_dressing_tables,
//    night_stands,
//    dining_packages,
//    dining_tables,
//    chairs,
//    sofa_and_sofa_beds,
//    armchairs_and_lounges,
//    sideboards_and_cabinets,
//    tv_units,
//    lounge_tables,
//    spot_lighting,
//    plafonds,
//    chandeliers_and_pendants,
//    wall_bracket_lamps,
//    reading_and_bedside_lamps,
//    floor_lamps,
//    kids_room,
//    console_tables,
//    hall_cabinets_and_hangers,
//    outdoor_furniture
//}
